# Generated by Django 3.1.3 on 2022-05-26 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hnpwine', '0002_product_product_description_ui'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_description_ui',
        ),
    ]
