# Generated by Django 3.1.3 on 2022-05-26 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hnpwine', '0004_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
