# Generated by Django 3.1.3 on 2022-05-29 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hnpwine', '0006_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
