# Generated by Django 3.1.3 on 2022-05-29 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hnpwine', '0008_auto_20220529_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=150)),
                ('order_date', models.DateTimeField()),
                ('order_quantity', models.IntegerField(default=0)),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hnpwine.product')),
            ],
        ),
    ]
