# Generated by Django 3.1.3 on 2022-03-22 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('bill_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField()),
                ('payment', models.BooleanField()),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('product_category_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('product_category_org', models.CharField(max_length=50)),
                ('product_category_image', models.ImageField(blank=True, null=True, upload_to='gallery')),
                ('product_category_description', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_code', models.CharField(max_length=20, unique=True)),
                ('product_name', models.CharField(max_length=150)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='gallery')),
                ('product_vote', models.IntegerField(default=0)),
                ('product_price', models.IntegerField()),
                ('product_description', models.CharField(blank=True, max_length=150, null=True)),
                ('product_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ntnwine.productcategory')),
            ],
        ),
        migrations.CreateModel(
            name='BillOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('bill_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ntnwine.bill')),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ntnwine.product')),
            ],
        ),
    ]
