# Generated by Django 3.1.3 on 2020-11-22 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20201122_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(default='High', max_length=50),
            preserve_default=False,
        ),
    ]
