# Generated by Django 3.1.3 on 2022-03-14 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_product_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('product_category_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('product_category_org', models.CharField(max_length=50)),
                ('product_category_desciption', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
