# Generated by Django 3.1.3 on 2022-03-14 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_productcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='product_category_image',
            field=models.ImageField(blank=True, null=True, upload_to='gallery'),
        ),
    ]
