# Generated by Django 3.1.3 on 2022-03-15 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20220314_0804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_type',
            new_name='product_type_id',
        ),
    ]
