# Generated by Django 3.1.3 on 2022-03-15 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20220315_0150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_type_id',
            new_name='product_category_name',
        ),
    ]
