# Generated by Django 3.1.3 on 2022-03-15 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20220315_0151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_category_name',
            new_name='product_category',
        ),
    ]
